//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelCuiHuaJi.KnapsacksService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfLong", Namespace="http://LiweijianWeb.com/", ItemName="long")]
    [System.SerializableAttribute()]
    public class ArrayOfLong : System.Collections.Generic.List<long> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://LiweijianWeb.com/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://LiweijianWeb.com/", ConfigurationName="KnapsacksService.KnapsacksServiceSoap")]
    public interface KnapsacksServiceSoap {
        
        // CODEGEN: 命名空间 http://LiweijianWeb.com/ 的元素名称 values 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://LiweijianWeb.com/GetGroupIdsByKnapsacks", ReplyAction="*")]
        ExcelCuiHuaJi.KnapsacksService.GetGroupIdsByKnapsacksResponse GetGroupIdsByKnapsacks(ExcelCuiHuaJi.KnapsacksService.GetGroupIdsByKnapsacksRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGroupIdsByKnapsacksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGroupIdsByKnapsacks", Namespace="http://LiweijianWeb.com/", Order=0)]
        public ExcelCuiHuaJi.KnapsacksService.GetGroupIdsByKnapsacksRequestBody Body;
        
        public GetGroupIdsByKnapsacksRequest() {
        }
        
        public GetGroupIdsByKnapsacksRequest(ExcelCuiHuaJi.KnapsacksService.GetGroupIdsByKnapsacksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://LiweijianWeb.com/")]
    public partial class GetGroupIdsByKnapsacksRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExcelCuiHuaJi.KnapsacksService.ArrayOfLong values;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ExcelCuiHuaJi.KnapsacksService.ArrayOfLong capacities;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int scaleNum;
        
        public GetGroupIdsByKnapsacksRequestBody() {
        }
        
        public GetGroupIdsByKnapsacksRequestBody(ExcelCuiHuaJi.KnapsacksService.ArrayOfLong values, ExcelCuiHuaJi.KnapsacksService.ArrayOfLong capacities, int scaleNum) {
            this.values = values;
            this.capacities = capacities;
            this.scaleNum = scaleNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGroupIdsByKnapsacksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGroupIdsByKnapsacksResponse", Namespace="http://LiweijianWeb.com/", Order=0)]
        public ExcelCuiHuaJi.KnapsacksService.GetGroupIdsByKnapsacksResponseBody Body;
        
        public GetGroupIdsByKnapsacksResponse() {
        }
        
        public GetGroupIdsByKnapsacksResponse(ExcelCuiHuaJi.KnapsacksService.GetGroupIdsByKnapsacksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://LiweijianWeb.com/")]
    public partial class GetGroupIdsByKnapsacksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExcelCuiHuaJi.KnapsacksService.ArrayOfAnyType GetGroupIdsByKnapsacksResult;
        
        public GetGroupIdsByKnapsacksResponseBody() {
        }
        
        public GetGroupIdsByKnapsacksResponseBody(ExcelCuiHuaJi.KnapsacksService.ArrayOfAnyType GetGroupIdsByKnapsacksResult) {
            this.GetGroupIdsByKnapsacksResult = GetGroupIdsByKnapsacksResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KnapsacksServiceSoapChannel : ExcelCuiHuaJi.KnapsacksService.KnapsacksServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KnapsacksServiceSoapClient : System.ServiceModel.ClientBase<ExcelCuiHuaJi.KnapsacksService.KnapsacksServiceSoap>, ExcelCuiHuaJi.KnapsacksService.KnapsacksServiceSoap {
        
        public KnapsacksServiceSoapClient() {
        }
        
        public KnapsacksServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KnapsacksServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KnapsacksServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KnapsacksServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExcelCuiHuaJi.KnapsacksService.GetGroupIdsByKnapsacksResponse ExcelCuiHuaJi.KnapsacksService.KnapsacksServiceSoap.GetGroupIdsByKnapsacks(ExcelCuiHuaJi.KnapsacksService.GetGroupIdsByKnapsacksRequest request) {
            return base.Channel.GetGroupIdsByKnapsacks(request);
        }
        
        public ExcelCuiHuaJi.KnapsacksService.ArrayOfAnyType GetGroupIdsByKnapsacks(ExcelCuiHuaJi.KnapsacksService.ArrayOfLong values, ExcelCuiHuaJi.KnapsacksService.ArrayOfLong capacities, int scaleNum) {
            ExcelCuiHuaJi.KnapsacksService.GetGroupIdsByKnapsacksRequest inValue = new ExcelCuiHuaJi.KnapsacksService.GetGroupIdsByKnapsacksRequest();
            inValue.Body = new ExcelCuiHuaJi.KnapsacksService.GetGroupIdsByKnapsacksRequestBody();
            inValue.Body.values = values;
            inValue.Body.capacities = capacities;
            inValue.Body.scaleNum = scaleNum;
            ExcelCuiHuaJi.KnapsacksService.GetGroupIdsByKnapsacksResponse retVal = ((ExcelCuiHuaJi.KnapsacksService.KnapsacksServiceSoap)(this)).GetGroupIdsByKnapsacks(inValue);
            return retVal.Body.GetGroupIdsByKnapsacksResult;
        }
    }
}
